# Agenda

1. NumPy
2. Pandas series
3. Data frames
4. Indexes, sorting, grouping
5. Dates + times
6. Optimization of time + space

Repo is here: https://github.com/reuven/Apple-2025-autumn-Python/tree/main

# NumPy?


In [1]:
x = 10

In [2]:
import sys
sys.getsizeof(x)

28

In [3]:
x = 100_000_000_000_000

sys.getsizeof(x)

32

In [4]:
x = x ** 20

In [5]:
sys.getsizeof(x)

152

In [6]:
import numpy as np

In [7]:
# n-dimensional array
np.ndarray

numpy.ndarray

In [8]:
np.array([10, 20, 30, 40, 50, 60])

array([10, 20, 30, 40, 50, 60])

In [9]:
a = np.array([10, 20, 30, 40, 50, 60])

In [10]:
type(a)

numpy.ndarray

In [11]:
a

array([10, 20, 30, 40, 50, 60])

In [12]:
a[0]

np.int64(10)

In [13]:
type(a[0])

numpy.int64

In [14]:
mylist = [10, 20, 30, 40, 50, 60]

mylist[0]

10

In [15]:
type(mylist[0])

int

In [16]:
repr(a[0])

'np.int64(10)'

In [17]:
a

array([10, 20, 30, 40, 50, 60])

In [18]:
a[0]

np.int64(10)

In [19]:
a[1]

np.int64(20)

In [20]:
a[2:6]

array([30, 40, 50, 60])

In [22]:
a.sum()

np.int64(210)

In [23]:
a.mean()

np.float64(35.0)

In [24]:
a.std()  # std deviation

np.float64(17.07825127659933)

In [25]:
a.min()

np.int64(10)

In [27]:
a.max()  # run the method on the instance

np.int64(60)

In [28]:
np.max(a)     # run the method on the class, passing the instance as argument

np.int64(60)

In [30]:
s = 'abcd'

s.upper()  # -> str.upper(s)

'ABCD'

In [31]:
a

array([10, 20, 30, 40, 50, 60])

In [32]:
mylist1 = [10, 20, 30]
mylist2 = [40, 50, 60]

mylist1 + mylist2

[10, 20, 30, 40, 50, 60]

In [33]:
a1 = np.array([10, 20, 30])
a2 = np.array([40, 50, 60])

a1 + a2

array([50, 70, 90])

In [34]:
64 * 3

192

In [35]:
sys.getsizeof(a1)

136

In [36]:
a1 = np.array([10, 20, 30, 31])
a2 = np.array([40, 50, 60])

a1 + a2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [38]:
a / a  # truediv -- always gives a float

array([1., 1., 1., 1., 1., 1.])

In [39]:
a // a   # floordiv -- always gives an int, does NOT round

array([1, 1, 1, 1, 1, 1])

# Broadcast

In [40]:
a

array([10, 20, 30, 40, 50, 60])

In [41]:
mylist

[10, 20, 30, 40, 50, 60]

In [42]:
mylist + 5

TypeError: can only concatenate list (not "int") to list

In [43]:
a + 5   # runs +5 on each element, and gives a new array back

array([15, 25, 35, 45, 55, 65])

In [44]:
a

array([10, 20, 30, 40, 50, 60])

In [45]:
a / 5

array([ 2.,  4.,  6.,  8., 10., 12.])

In [46]:
a ** 2

array([ 100,  400,  900, 1600, 2500, 3600])

In [47]:
a[0]= 123
a

array([123,  20,  30,  40,  50,  60])

In [48]:
a

array([123,  20,  30,  40,  50,  60])

# Other ways to create a NumPy array

1. `np.arange` -- similar to `range` in Python

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [52]:
# np.random.randint

np.random.randint(0, 100, 10)

array([21, 20, 86,  3, 12,  6, 83, 72, 66, 37])

In [53]:
np.random.randint(0, 100, 10)

array([67, 79, 27, 78, 83, 53, 20,  6, 29, 93])

In [54]:
np.random.seed(0) 
np.random.randint(0, 100, 10)

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

In [55]:
np.random.seed(0) 
np.random.randint(0, 100, 10)

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

In [56]:
# np.random.rand

np.random.rand(10)

array([0.891773  , 0.96366276, 0.38344152, 0.79172504, 0.52889492,
       0.56804456, 0.92559664, 0.07103606, 0.0871293 , 0.0202184 ])

In [57]:
np.random.rand(10) * 100

array([83.26198455, 77.81567509, 87.00121482, 97.86183422, 79.91585642,
       46.14793623, 78.05291763, 11.82744259, 63.99210213, 14.33532874])

In [58]:
help(np.random.rand)

Help on method rand in module numpy.random:

rand(*args) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)

    Random values in a given shape.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.

    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.

    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.

    See Also
    --------
    random

    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.1402247