# Agenda

1. NumPy
2. Pandas series
3. Data frames
4. Indexes, sorting, grouping
5. Dates + times
6. Optimization of time + space

Repo is here: https://github.com/reuven/Apple-2025-autumn-Python/tree/main

# NumPy?


In [1]:
x = 10

In [2]:
import sys
sys.getsizeof(x)

28

In [3]:
x = 100_000_000_000_000

sys.getsizeof(x)

32

In [4]:
x = x ** 20

In [5]:
sys.getsizeof(x)

152

In [6]:
import numpy as np

In [7]:
# n-dimensional array
np.ndarray

numpy.ndarray

In [8]:
np.array([10, 20, 30, 40, 50, 60])

array([10, 20, 30, 40, 50, 60])

In [9]:
a = np.array([10, 20, 30, 40, 50, 60])

In [10]:
type(a)

numpy.ndarray

In [11]:
a

array([10, 20, 30, 40, 50, 60])

In [12]:
a[0]

np.int64(10)

In [13]:
type(a[0])

numpy.int64

In [14]:
mylist = [10, 20, 30, 40, 50, 60]

mylist[0]

10

In [15]:
type(mylist[0])

int

In [16]:
repr(a[0])

'np.int64(10)'

In [17]:
a

array([10, 20, 30, 40, 50, 60])

In [18]:
a[0]

np.int64(10)

In [19]:
a[1]

np.int64(20)

In [20]:
a[2:6]

array([30, 40, 50, 60])

In [22]:
a.sum()

np.int64(210)

In [23]:
a.mean()

np.float64(35.0)

In [24]:
a.std()  # std deviation

np.float64(17.07825127659933)

In [25]:
a.min()

np.int64(10)

In [27]:
a.max()  # run the method on the instance

np.int64(60)

In [28]:
np.max(a)     # run the method on the class, passing the instance as argument

np.int64(60)

In [30]:
s = 'abcd'

s.upper()  # -> str.upper(s)

'ABCD'

In [31]:
a

array([10, 20, 30, 40, 50, 60])

In [32]:
mylist1 = [10, 20, 30]
mylist2 = [40, 50, 60]

mylist1 + mylist2

[10, 20, 30, 40, 50, 60]

In [33]:
a1 = np.array([10, 20, 30])
a2 = np.array([40, 50, 60])

a1 + a2

array([50, 70, 90])

In [34]:
64 * 3

192

In [35]:
sys.getsizeof(a1)

136

In [36]:
a1 = np.array([10, 20, 30, 31])
a2 = np.array([40, 50, 60])

a1 + a2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [38]:
a / a  # truediv -- always gives a float

array([1., 1., 1., 1., 1., 1.])

In [39]:
a // a   # floordiv -- always gives an int, does NOT round

array([1, 1, 1, 1, 1, 1])

# Broadcast

In [40]:
a

array([10, 20, 30, 40, 50, 60])

In [41]:
mylist

[10, 20, 30, 40, 50, 60]

In [42]:
mylist + 5

TypeError: can only concatenate list (not "int") to list

In [43]:
a + 5   # runs +5 on each element, and gives a new array back

array([15, 25, 35, 45, 55, 65])

In [44]:
a

array([10, 20, 30, 40, 50, 60])

In [45]:
a / 5

array([ 2.,  4.,  6.,  8., 10., 12.])

In [46]:
a ** 2

array([ 100,  400,  900, 1600, 2500, 3600])

In [47]:
a[0]= 123
a

array([123,  20,  30,  40,  50,  60])

In [48]:
a

array([123,  20,  30,  40,  50,  60])

# Other ways to create a NumPy array

1. `np.arange` -- similar to `range` in Python

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [52]:
# np.random.randint

np.random.randint(0, 100, 10)

array([21, 20, 86,  3, 12,  6, 83, 72, 66, 37])

In [53]:
np.random.randint(0, 100, 10)

array([67, 79, 27, 78, 83, 53, 20,  6, 29, 93])

In [54]:
np.random.seed(0) 
np.random.randint(0, 100, 10)

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

In [55]:
np.random.seed(0) 
np.random.randint(0, 100, 10)

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

In [56]:
# np.random.rand

np.random.rand(10)

array([0.891773  , 0.96366276, 0.38344152, 0.79172504, 0.52889492,
       0.56804456, 0.92559664, 0.07103606, 0.0871293 , 0.0202184 ])

In [57]:
np.random.rand(10) * 100

array([83.26198455, 77.81567509, 87.00121482, 97.86183422, 79.91585642,
       46.14793623, 78.05291763, 11.82744259, 63.99210213, 14.33532874])

In [59]:
help(np.max)

Help on method descriptor max in module numpy:

max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>
)
    Return the maximum of an array or maximum along an axis.

    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used. If this is a tuple of ints, the maximum is selected over
        multiple axes, instead of a single axis or all the axes as before.

    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See :ref:`ufuncs-output-type` for more details.

    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will broadcast correctl

In [60]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Exercises: NumPy arrays

1. Define a NumPy array with 3 elements, your birthday (year, month, day)
2. Change the year to be this year.
3. Create a new array with 10 ints from 0-100.
4. Find the mean and std of these numbers.
5. Create a new array with 10 floats from 0-1,000.
6. Find the mean and std of these numbers.

In [62]:
10+10
20+20
30+30

60

In [63]:
birthday = np.array([1970, 7, 14])
birthday

array([1970,    7,   14])

In [64]:
type(birthday)

numpy.ndarray

In [65]:
type(birthday[0])

numpy.int64

In [66]:
birthday[0] = 2025
birthday

array([2025,    7,   14])

In [67]:
np.random.seed(0)
a = np.random.randint(0, 100, 10)
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

In [68]:
a - 10

array([34, 37, 54, 57, 57, -1, 73, 11, 26, 77])

In [69]:
a + a

array([ 88,  94, 128, 134, 134,  18, 166,  42,  72, 174])

In [70]:
a * 2

array([ 88,  94, 128, 134, 134,  18, 166,  42,  72, 174])

In [73]:
np.random.seed(0)
a = np.random.rand(10) * 1000
a

array([548.81350393, 715.18936637, 602.76337607, 544.883183  ,
       423.65479934, 645.89411307, 437.58721126, 891.77300078,
       963.6627605 , 383.44151883])

In [74]:
a + a

array([1097.62700785, 1430.37873274, 1205.52675214, 1089.76636599,
        847.30959868, 1291.78822613,  875.17442253, 1783.54600156,
       1927.325521  ,  766.88303765])

In [75]:
a * 3

array([1646.44051178, 2145.56809912, 1808.29012821, 1634.64954899,
       1270.96439802, 1937.6823392 , 1312.76163379, 2675.31900235,
       2890.9882815 , 1150.32455648])

In [76]:
a.mean()

np.float64(615.7662833145425)

In [77]:
a.std()

np.float64(184.47489445957166)

In [78]:
a

array([548.81350393, 715.18936637, 602.76337607, 544.883183  ,
       423.65479934, 645.89411307, 437.58721126, 891.77300078,
       963.6627605 , 383.44151883])

In [79]:
# I want the item at index 2

a[2]

np.float64(602.7633760716438)

In [80]:
# I want the item from index 5

a[5]

np.float64(645.8941130666561)

In [82]:
# I want the items at index 2 + 5

a[ [2, 5] ]    # "fancy indexing"

array([602.76337607, 645.89411307])

In [83]:
a[ [2, 5, 2, 5, 2, 5] ]

array([602.76337607, 645.89411307, 602.76337607, 645.89411307,
       602.76337607, 645.89411307])

In [84]:
a = np.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [86]:
# I can also do this:
# this is known as a "boolean index" or a "mask index"
# Wherever it's True, I get the value. Where it's False, I don't.

a[ [True, False, False, True] ]

array([10, 40])

In [87]:
# broadcast with comparison

a < 30

array([ True,  True, False, False])

In [88]:
a[ a<30 ]

array([10, 20])

In [89]:
a[ a<a.mean() ]

array([10, 20])

# Exercises with boolean index

1. Create a NumPy array with 20 random ints from 0-100.
2. What is the smallest number that is bigger than 50?
3. What is the largest number that is less than the mean - 1 std?
4. Calculate the mean from numbers that are less than the mean.

In [90]:
a.max()

np.int64(40)

In [91]:
a.min()

np.int64(10)

In [92]:
a.mean()

np.float64(25.0)

In [93]:
# 1. Create a NumPy array with 20 random ints from 0-100.

np.random.seed(0)
a = np.random.randint(0, 100, 20)
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88])

In [96]:
# 2. What is the smallest number that is bigger than 50?

a[a > 50].min()

np.int64(58)

In [97]:
mean

NameError: name 'mean' is not defined

In [104]:
np.random.seed(0)
a = np.random.randint(0, 100, 20_000)


In [105]:
%timeit a[a<50].min()

39.2 μs ± 603 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [106]:
%timeit min(a[a<50])

281 μs ± 1.56 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [110]:
# 3. What is the largest number that is less than the mean - 1 std?

np.random.seed(0)
a = np.random.randint(0, 100, 20)

a[a < a.mean() - a.std()].max()

np.int64(21)

In [113]:
# 4. Calculate the mean from numbers that are less than the mean.

a[a < a.mean()].mean()

np.float64(34.666666666666664)

In [114]:
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88])

In [115]:
# get all of the odd numbers

a[a % 2]

array([44, 47, 44, 47, 47, 47, 47, 47, 44, 47, 44, 44, 44, 44, 44, 47, 47,
       47, 44, 44])

In [116]:
a%2

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0])

In [117]:
a[a%2==1]

array([47, 67, 67,  9, 83, 21, 87, 65, 39, 87])

In [119]:
# I want all of the odd numbers less than the mean

a[ a%2==1  and  a<a.mean() ] 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# In Python -- boolean context

Everything in the context (`if`, `and`, `or`, `not`) is turned into a boolean, and everything is `True` except for:

- `False`
- `None`
- 0
- anything empty (e.g., `''`)

# NumPy boolean operators

- `and` is `&`
- `or` is `|`
- `not` is `~`

In [121]:
a[ (a%2==1)  &  (a<a.mean()) ] 

array([47,  9, 21, 39])

In [122]:
a[ (a%2==1)  &
   (a<a.mean()) ] 

array([47,  9, 21, 39])

# Exercise: Complex queries

1. Create an array with 20 random ints from 0-1,000.
2. Find all of the numbers that are either smaller than the mean-1 std or bigger than the mean + 1 std.
3. Find all of the odd numbers below the mean, and all of the even numbers bigger than the mean.

In [125]:
np.random.seed(0)
a = np.random.randint(0, 1000, 20)
a

array([684, 559, 629, 192, 835, 763, 707, 359,   9, 723, 277, 754, 804,
       599,  70, 472, 600, 396, 314, 705])

In [130]:
a[(a < a.mean() - a.std()) |
  (a > a.mean() + a.std())]

array([192, 835,   9, 277, 804,  70])

In [136]:
%timeit a[((a%2 == 1) & (a < a.mean()))  | (a%2 == 0) & (a > a.mean())]

6.28 μs ± 65.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [132]:
a.mean()

np.float64(522.55)

In [134]:
odd_mask_array = a%2 == 1

In [135]:
%timeit a[(odd_mask_array & (a < a.mean()))  | ~odd_mask_array & (a > a.mean())]

4.68 μs ± 30.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [137]:
a & 3 

array([0, 3, 1, 0, 3, 3, 3, 3, 1, 3, 1, 2, 0, 3, 2, 0, 0, 0, 2, 1])

In [138]:
%timeit a[((a&1) & (a < a.mean()))  | (a&1) & (a > a.mean())]

5.51 μs ± 79.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [142]:
%%timeit 
bitwise_add = a&1
a[(bitwise_add & (a < a.mean()))  | ~bitwise_add & (a > a.mean())]

5.35 μs ± 37.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
