# Agenda

1. NumPy
2. Pandas series
3. Data frames
4. Indexes, sorting, grouping
5. Dates + times
6. Optimization of time + space

Repo is here: https://github.com/reuven/Apple-2025-autumn-Python/tree/main

# NumPy?


In [1]:
x = 10

In [2]:
import sys
sys.getsizeof(x)

28

In [3]:
x = 100_000_000_000_000

sys.getsizeof(x)

32

In [4]:
x = x ** 20

In [5]:
sys.getsizeof(x)

152

In [6]:
import numpy as np

In [7]:
# n-dimensional array
np.ndarray

numpy.ndarray

In [8]:
np.array([10, 20, 30, 40, 50, 60])

array([10, 20, 30, 40, 50, 60])

In [9]:
a = np.array([10, 20, 30, 40, 50, 60])

In [10]:
type(a)

numpy.ndarray

In [11]:
a

array([10, 20, 30, 40, 50, 60])

In [12]:
a[0]

np.int64(10)

In [13]:
type(a[0])

numpy.int64

In [14]:
mylist = [10, 20, 30, 40, 50, 60]

mylist[0]

10

In [15]:
type(mylist[0])

int

In [16]:
repr(a[0])

'np.int64(10)'

In [17]:
a

array([10, 20, 30, 40, 50, 60])

In [18]:
a[0]

np.int64(10)

In [19]:
a[1]

np.int64(20)

In [20]:
a[2:6]

array([30, 40, 50, 60])

In [22]:
a.sum()

np.int64(210)

In [23]:
a.mean()

np.float64(35.0)

In [24]:
a.std()  # std deviation

np.float64(17.07825127659933)

In [25]:
a.min()

np.int64(10)

In [27]:
a.max()  # run the method on the instance

np.int64(60)

In [28]:
np.max(a)     # run the method on the class, passing the instance as argument

np.int64(60)

In [30]:
s = 'abcd'

s.upper()  # -> str.upper(s)

'ABCD'

In [31]:
a

array([10, 20, 30, 40, 50, 60])